name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - run: |
          cd spatgris-man-en/
          mdbook build
          cd ..
          cd spatgris-man-fr/
          mdbook build
          cd ..
          mkdir github-page
          mv index.html github-page
          mkdir github-page/francais
          mkdir github-page/english
          mv spatgris-man-fr/book/* github-page/francais
          mv spatgris-man-en/book/* github-page/english

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github-page
